using POC.Shared.Domain.Fixed;
using POC.Shared.Domain.ValueObjects;
using System;
using System.Collections.Generic;

namespace POC.Bff.Web.Domain.Responses
{
    public class PvSystemListResponse
    {
        public Guid Id { get; set; }
        public Guid? SelectedPromotionId { get; set; }
        public string SelectedPromotionName { get; set; }
        public bool AutoGenerated { get; set; }
        public decimal Power { get; set; }
        public string PowerLabel { get; set; }
        public decimal PvSystemPrice { get; set; }
        public decimal InsurancePrice { get; set; }
        public object PvSystemParams { get; set; }
        public List<SystemComponentResponse> ComponentList { get; set; }
        public List<object> InsuranceList { get; set; }
        public decimal? PvSystemMarkup { get; set; }
        public decimal? PvSystemCmv { get; set; }
        public decimal? PvSystemTax { get; set; }
        public string PvSystemModel { get; set; }
    }


    public class SystemComponentResponse
    {
        public ComponentType Type { get; set; }
        public ErpCode ErpCode { get; set; }
        public string Model { get; set; }
        public decimal Price { get; set; }
        public decimal Power { get; set; }
        public int Quantity { get; set; }
        public string KeyName { get; set; }
        public string ImageKeyName { get; set; }
        public bool IsOutOfStock { get; set; }
    }
}