using System;
using System.Collections.Generic;

namespace POC.Bff.Web.Domain.Responses
{
    public class SystemResponse
    {
        public Guid? Id { get; set; }

        public Guid? SelectedPromotionId { get; set; }

        public bool? AutoGenerated { get; set; }

        public decimal? Power { get; set; }

        public string PowerLabel { get; set; }

        public decimal? Price { get; set; }

        public decimal? InsurancePrice { get; set; }

        public object PvSystemParams { get; set; }

        public List<object> Components { get; set; }

        public List<object> Insurances { get; set; }
    }
}