using POC.Shared.Domain.Fixed;
using POC.Shared.Domain.ValueObjects;
using System;
using System.Collections.Generic;

namespace POC.Bff.Web.Domain.Dtos
{
    public class PvSystemListDto
    {
        public Guid Id { get; set; }
        public Guid? SelectedPromotionId { get; set; }
        public string SelectedPromotionName { get; set; }
        public bool AutoGenerated { get; set; }
        public decimal Power { get; set; }
        public string PowerLabel { get; set; }
        public decimal Price { get; set; }
        public decimal InsurancePrice { get; set; }
        public object PvSystemParams { get; set; }
        public List<SystemComponentDto> ComponentList { get; set; }
        public List<object> InsuranceList { get; set; }
        public decimal? PvSystemMarkup { get; set; }
        public decimal? PvSystemCmv { get; set; }
        public decimal? PvSystemTax { get; set; }
        public string PvSystemModel { get; set; }
    }

    public class SystemComponentDto
    {
        public ComponentType Type { get; set; }
        public ErpCode ErpCode { get; set; }
        public string Model { get; set; }
        public decimal Price { get; set; }
        public decimal Power { get; set; }
        public int Quantity { get; set; }
        public bool IsOutOfStock { get; set; }
        public decimal Cmv { get; set; }
        public decimal Tax { get; set; }
    }
}