using System;
using System.Collections.Generic;

namespace POC.Bff.Web.Domain.Dtos
{
    public class SystemDto
    {
        public Guid? Id { get; set; }

        public Guid? SelectedPromotionId { get; set; }

        public string SelectedPromotionName { get; set; }

        public bool? AutoGenerated { get; set; }

        public decimal? Power { get; set; }

        public string PowerLabel { get; set; }

        public decimal? Price { get; set; }

        public decimal? InsurancePrice { get; set; }

        public object PvSystemParams { get; set; }

        public List<object> ComponentList { get; set; }

        public List<object> InsuranceList { get; set; }

        public decimal PvSystemMarkup { get; set; }

        public decimal PvSystemCmv { get; set; }

        public decimal PvSystemTax { get; set; }
    }
}